apps/accounts/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, patterns
from accounts.views.active_sessions import active_sessions
from accounts.views.active_sessions_ajax import active_sessions_ajax
from accounts.views.ping import ping


urlpatterns = patterns('',
                       url(r'ping/$', ping, name='ping'),
                       url(r'active_sessions/$', active_sessions, name='active_sessions'),
                       url(r'active_sessions/ajax/$', active_sessions_ajax, name='active_sessions_ajax'),
                       )

leadfrod/urls.py
from django.conf.urls import patterns, url, include
#from staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin


admin.autodiscover()
import settings


urlpatterns = patterns('',
                       # Example:
                       # (r'^leap/', include('leap.foo.urls')),
                       (r'^$', 'rotator.views.index'),
                       (r'^(static|media)/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       (r'^accounts/login/$', 'django.contrib.auth.views.login'),
                       url(r'^next/?$', 'rotator.views.next_workitem', name='next_workitem'),
                       (r'^submit/?$', 'rotator.views.submit_workitem'),
                       url(r'^logout/?$', 'rotator.views.click_logout', name='logout'),
                       (r'^dailycap/?$', 'rotator.views.admin_manage_dailycap'),
                       (r'^release/?$', 'rotator.views.admin_release_lead'),
                       (r'^locked_leads/?$', 'rotator.views.admin_show_locked_leads'),
                       (r'^delete_file$', 'rotator.views.admin_delete_csvfile_raw'),
                       (r'^files/?$', 'rotator.views.admin_show_csvfiles'),
                       (r'^th/(?P<owner>.+)/$', 'rotator.views.trafficholder_callback'),
                       (r'^revenue/month/$', 'rotator.views.month_revenue'),
                       (r'^manualqueue/create/$', 'rotator.views.manualQueueCreate'),
                       (r'^manualqueue/go/$', 'rotator.views.manualQueueGo'),
                       (r'^showqueue/$', 'rotator.views.showQueue'),
                       (r'^azoogle/accounts/$', 'rotator.views.azoogleAccounts'),
                       (r'^azoogle/earnings/save/$', 'rotator.views.azoogleEarningsSave'),

                       (r'^spyder/(?P<site>.+)?$', 'rotator.views.spyder'),

                       #API views
                       (r'^dailysummary/$', 'rotator.apis.show_daily_summary'),

                       url(r'^offer/(?P<offer_id>\d+)/changestatus/', 'rotator.views.offer_changestatus', name="changeOfferStatus"),
                       # Uncomment the next line to enable the admin:
                       (r'^admin/', include(admin.site.urls)),
                       (r'^ajax/admin/', include('locking.urls')),
                       url(r'accounts/', include('accounts.urls', namespace='accounts')),

)

#urlpatterns += staticfiles_urlpatterns()

apps/accounts/models/session.py
# -*- coding:utf-8 -*-
import datetime

from django.db import models
from django.utils.timezone import now


SESSION_EXPIRE_IN = 60


class UserSessionManager(models.Manager):
    def active_sessions(self):
        active_datetime = now() - datetime.timedelta(seconds=SESSION_EXPIRE_IN)
        return self.filter(datetime_last_activity__gte=active_datetime)

    def update_active_session(self, user):
        try:
            session = self.active_sessions().filter(user=user).order_by('-id')[0]
        except IndexError:
            session = self.create(user=user)
        session.save()


class UserSession(models.Model):
    user = models.ForeignKey('auth.User')
    datetime_login = models.DateTimeField()
    datetime_last_activity = models.DateTimeField()

    objects = UserSessionManager()

    class Meta:
        app_label = 'accounts'

    @property
    def session_duration(self):
        return self.datetime_last_activity - self.datetime_login

    @property
    def active(self):
        return self.datetime_last_activity > (now() - datetime.timedelta(seconds=SESSION_EXPIRE_IN))

    def save(self, *args, **kwargs):
        if self.id is None:
            self.datetime_login = now()
        self.datetime_last_activity = now()
        super(UserSession, self).save(*args, **kwargs)

apps/rotator/models/account.py
# -*- coding:utf-8 -*-
import datetime
from django.db import models
from django.utils.timezone import now
from rotator.models import PAYMENT_TYPE_LIST, STATUS_LIST, ACTIVE


class Account(models.Model):
    network = models.ForeignKey('rotator.Network', related_name='accounts')
    company = models.ForeignKey('rotator.Company', related_name='accounts')

    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30, null=True, blank=True)
    user_id = models.CharField(max_length=255, null=True, blank=True)
    AM = models.CharField(max_length=30)
    phone = models.CharField(max_length=30, null=True, blank=True)
    AM_phone_list = models.CharField(max_length=30, null=True, blank=True)
    AM_email_list = models.CharField(max_length=30, null=True, blank=True)
    AM_IM_list = models.CharField(max_length=30, null=True, blank=True)
    recieved_check_once = models.BooleanField(default=False, blank=True)
    stats_configured = models.BooleanField(default=False, blank=True)
    payments_via = models.CharField(max_length=30, choices=PAYMENT_TYPE_LIST)
    last_payment_date = models.DateTimeField(null=True, blank=True)
    payment_frequency = models.CharField(max_length=30, null=True, blank=True)
    daily_cap = models.FloatField(default=100)
    capacity = models.FloatField(default=100)
    status = models.CharField(max_length=30, choices=STATUS_LIST,
                              default=ACTIVE)
    description = models.CharField(max_length=255, null=True, blank=True)
    last_checked = models.DateTimeField(null=True, blank=True)
    today_revenue = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    primary = models.BooleanField(default=True)

    def owner(self):
        return self.company.owner

    owner.short_description = "Owner"

    def is_active(self):
        return self.status == ACTIVE

    def checked(self):
        self.last_checked = now()
        self.save()

    def setRevenue(self, revenue):
        self.today_revenue = revenue
        self.save()

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
        ordering = ['username', 'capacity']
        app_label = 'rotator'

    def __unicode__(self):
        return u'%s,%s,%s[%s/%s]' % (self.company, self.network, self.username, self.capacity, self.daily_cap)

apps/rotator/models/advertiser.py
# -*- coding:utf-8 -*-
from django.db import models
from rotator.models import STATUS_LIST, ACTIVE


class Advertiser(models.Model):
    name = models.CharField(max_length=30)
    daily_cap = models.FloatField(default=25)
    status = models.CharField(max_length=30, choices=STATUS_LIST)
    description = models.CharField(max_length=255, null=True, blank=True)

    def is_active(self):
        return self.status == ACTIVE

    def numberOfAccounts(self):
        return self.account_capacity.count()

    numberOfAccounts.short_description = u"Account qty"

    def clearCapacityOfAllAccounts(self):
        self.account_capacity.all().update(capacity=self.daily_cap)

    def getAccountCapacity(self, adv_account):
        from rotator.models.advertiser_account_capacity import AdvertiserAccountCapacity
        if AdvertiserAccountCapacity.objects.filter(advertiser=self, account=adv_account).exists():
            return self.account_capacity.get(account=adv_account)
        return None

    @property
    def getAccounts(self):
        return self.account_capacity.all()

    class Meta:
        verbose_name = 'Advertiser'
        verbose_name_plural = 'Advertisers'
        ordering = ['name']
        app_label = 'rotator'

    def __unicode__(self):
        return u'%s' % self.name

apps/rotator/models/csv_file.py
# -*- coding:utf-8 -*-
import csv
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Q
from django.utils.timezone import now
import os
from locking.managers import point_of_timeout
from rotator.models import STATUS_LIST, ACTIVE
from django.conf import settings


class CSVFile(models.Model):
    lead_source = models.ForeignKey('rotator.LeadSource')
    niche = models.ForeignKey('rotator.Niche')
    filename = models.CharField(max_length=255, null=True, blank=True, unique=True)
    filesize = models.IntegerField(default=0)
    date_time = models.DateTimeField(default=now)
    uploaded_by = models.CharField(max_length=30)
    cost = models.FloatField(default=0)
    workers = models.ManyToManyField(User, null=True, blank=True,
                                     related_name='assignments')
    max_offers = models.FloatField(default=1)
    csv_headers = models.TextField(null=False, blank=True)
    status = models.CharField(max_length=30, choices=STATUS_LIST,
                              default=ACTIVE)
    description = models.CharField(max_length=255, null=True, blank=True)
    csv_files = models.FileField(upload_to=settings.LEAD_FILE_DIR,
                                 help_text='Make sure your CSV file has Excel format\
                             (fields are separated with a <tt>comma</tt>)')
    has_header = models.BooleanField(default=True,
                                     help_text='Whether uploading file has the first\
                                         row as a header')

    class Meta:
        verbose_name = 'CSV File'
        verbose_name_plural = 'CSV Files'
        app_label = 'rotator'

    @property
    def leads_count(self):
        return self.leads.count()

    def create_leads_from_file(self):
        """If there is an uploaded file but there is no leads it process them"""
        if not self.has_leads() and (self.csv_files and self.csv_files.name):

            csv_full_path = os.path.join(settings.MEDIA_ROOT, self.csv_files.name)
            with open(csv_full_path, 'rb') as csvFile:
                rows = csv.reader(csvFile)
                for idx, row in enumerate(rows):
                    if not row[0]:
                        continue
                    if idx == 0 and self.has_header:
                        self.csv_headers = ','.join(row)
                        continue
                    from rotator.models.lead import Lead
                    Lead.objects.create(csv=self, status=ACTIVE, lead_data=','.join(row))

    def has_leads(self):
        return self.leads_count > 0

    def locked_leads(self):
        timeout = point_of_timeout()
        return self.leads.filter(_locked_at__gt=timeout, _locked_at__isnull=False)

    def unlocked_leads(self):
        timeout = point_of_timeout()
        return self.leads.filter(Q(_locked_at__lte=timeout) | Q(_locked_at__isnull=True))

    def is_active(self):
        return self.status == ACTIVE

    def get_revenue(self):  # todo: unused
        return self.leads.aggregate(Sum('offers_completed__payout'))['offers_completed__payout__sum']

    def getPercentOfCompleted(self):  # todo: unused
        if self.leads_count == 0:
            return 0
        return self.leads.offers_completed.count() / self.leads.count() * 100

    def save(self, *args, **kwargs):
        if self.csv_files:
            self.filename = self.csv_files.name

        super(CSVFile, self).save(*args, **kwargs)
        self.create_leads_from_file()
        super(CSVFile, self).save(*args, **kwargs)

    def __unicode__(self):
        name = self.filename or self.csv_files.name
        return u'{} is {} uploaded by {} contains {} leads'.format(name, self.status, self.uploaded_by, self.leads_count)

apps/rotator/models/network.py
# -*- coding:utf-8 -*-
from django.db import models
from rotator.models import STATUS_LIST, ACTIVE


class Network(models.Model):
    name = models.CharField(max_length=30)
    url = models.CharField(max_length=100)
    single = models.BooleanField(default=True)
    status = models.CharField(max_length=30, choices=STATUS_LIST, default=ACTIVE)
    description = models.CharField(max_length=30, null=True, blank=True)

    def is_active(self):
        return self.status == ACTIVE

    class Meta:
        verbose_name = 'Network'
        verbose_name_plural = 'Networks'
        ordering = ['name']
        app_label = 'rotator'

    def __unicode__(self):
        return u'%s' % self.name

apps/accounts/views/active_sessions.py
# -*- coding:utf-8 -*-
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render_to_response
from django.template import RequestContext


@login_required
@user_passes_test(lambda u: u.is_superuser)
def active_sessions(request):
    return render_to_response('accounts/active_sessions.html', {}, context_instance=RequestContext(request))

apps/accounts/views/active_sessions_ajax.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponse
from json import dumps

from accounts.models import UserSession


@login_required
@user_passes_test(lambda u: u.is_superuser)
def active_sessions_ajax(request):
    actives = UserSession.objects.active_sessions().select_related('user__username')
    active_sesisons = []
    for s in actives:
        active_sesisons.append({
            'user': s.user.username,
            # 'logged_in': s.datetime_login,
            'duration': divmod(s.session_duration.seconds, 60)
        })

    return HttpResponse(dumps(active_sesisons))

apps/accounts/views/ping.py
# -*- coding:utf-8 -*-
from django.http import HttpResponse, HttpResponseForbidden
from json import dumps
from accounts.models import UserSession


def ping(request):
    if request.user.is_authenticated():
        UserSession.objects.update_active_session(request.user)
        return HttpResponse(dumps({}))
    else:
        return HttpResponseForbidden()

templates/accounts.html
VIEW ALL ACCOUNTS


LLC | ACCOUNT | [EDIT] [DELETE]

templates/admin_menu.html
DASHBOARD|OFFERS|ACCOUNTS|WORKER|OTHER->NETWORKS,OWNERS,LLC,IPSOLUTION,CONFIG|LOGOUT

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block head_title %}Leadfrod application{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
          padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet">
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-latest.min.js"></script>
  <!--[if lt IE 9]> <script src="{{ STATIC_URL }}js/html5shiv.js"></script> <![endif]-->
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    {% include "ping_session_include.html" %}
      {% block scripts %} {% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Dashboard</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href='{% url "accounts:active_sessions" %}'>Active user sessions</a></li>
                        <li><a href='#'>Offer Control</a></li>
                        <li><a href='#'>Worker Stats</a></li>
                        <li><a href='#'>ROI Report</a></li>
                        <li><a href='#'>Daily Cap</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Traffic <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href='#'>View Queue</a></li>
                        <li><a href='#'>Add Emergency Clicks</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Config <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href='#'>Postback, Pixel, API</a></li>
                        <li><a href='#'>Manual Subids</a></li>
                        <li><a href='#'>Network APIs and Spyders</a></li>
                        <li><a href='#'>Referer domains</a></li>
                        <li><a href='#'>System</a></li>
                    </ul>
                </li>
            </ul>
              <ul class="nav pull-right">
                  {% if user.is_authenticated %}
                      <li><a href="{% url "logout" %}?next=/">Logout {{ user }}</a></li>
{#                      <li class="nav-text"><span>Logged in as {{ user }}</span> </li>#}
                  {% else %}

                  {% endif %}
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <h1>{% block title %} {% endblock %}</h1>

        {% block content %}
        {% endblock %}

    </div>

  </body>
</html>




templates/csvfiles.html
{% extends "base.html" %}
{% block scripts %}

    <script type="text/javascript">
$(function() {
    $(".delete_file").bind('click', function() {
        var csvfile_id = $(this).attr('id').split("_")[1];
        var token = $("input[name=csrfmiddlewaretoken]").val();
        $.ajax({
            type: "POST",
            cache: false,
            url: '/delete_file',
            data: {'csvfile_id': csvfile_id, 'csrfmiddlewaretoken': token},
            success: function(data) {
                $.fancybox.hideActivity();
                if (data.code == 'OK') {
                    $("#row_" + csvfile_id).remove();
                } else {
                    alert(data.code + ':' + data.message);
                }
                return false;
            },
        }, 'json');
    });
});
</script>
{% endblock %}
{% block title %} List of CSV Files {% endblock %}
{% block content %}

    <table width="80%" border="1">
		<tr>
			<th>File info</th>
			<th>Action</th>
		</tr>
        {% for file in files %}
            <tr id="row_{{ file.id }}">
				<td align="left">{{ file }}</td>
				<td align="center"><a href="#" id="link_{{ file.id }}" class="delete_file">Delete</a></td>
			</tr>
        {% endfor %}
	</table>
    {% csrf_token %}
{% endblock %}

templates/daily_capacity.html
{% extends "base.html" %}

{% block title %} Dailycap reset {% endblock %}
{% block content %}

    {% if capacity %}
        <form action="/dailycap" method="post">
		{% csrf_token %}
		<input type="submit" value="Reset capacity"/>
	</form>
        <h2>{{ capacity.0.date }}</h2>
        <table width="90%" border="1">
		<tr>

            <th>Niche</th>
            <th>Owner</th>
            <th>Offer</th>
            <th>Account</th>
			<th>Offer ID</th>
            <th>Offer Capacity</th>
			<th>Advertiser Cap</th>
			<th>Account Cap</th>
			<th>Company Cap</th>
            <th>Owner Cap</th>
		</tr>
            {% for cap in capacity %}
                <tr>
                    <td>{{ cap.offer.niche }}</td>
                    <td>{{ cap.owner.name }}</td>
                    <td>{{ cap.offer.name }}</td>
                    <td>{{ cap.account.name }}</td>


				<td align="center">{{ cap.offer.offer_num }}</td>
				<td align="right">{{ cap.offer.capacity }}/{{ cap.offer.daily_cap }} <a href="/dailycap/{{ cap.offer_id }}">Reset</a></td>
				<td align="right">
					{% if cap.advertiser %}
                        {% if cap.advertiser.getAccounts.count > 1 %}
                            <OL>
								{% for acc in cap.advertiser.getAccounts %}
                                    <li>{{ acc.account.network.name }}&nbsp;{{ acc.account.username }}&nbsp;{{ acc.capacity }}/{{ cap.advertiser.daily_cap }}</li>
                                {% endfor %}
							</OL>
                        {% else %}
                            {{ cap.advertiser.getAccounts.0.account.network.name }}&nbsp;{{ cap.advertiser.getAccounts.0.account.username }}&nbsp;{{ cap.advertiser.getAccounts.0.capacity }}/
                            {{ cap.advertiser.daily_cap }}
                        {% endif %}
                    {% else %}
                        <tt>N/A</tt>
                    {% endif %}
				</td>
				<td align="right">{{ cap.account.capacity }}/{{ cap.account.daily_cap }}</td>
				<td align="right">{{ cap.company.capacity }}/{{ cap.company.daily_cap }}</td>
                <td align="right">{{ cap.owner.capacity }}/{{ cap.owner.daily_cap }}</td>
			</tr>
            {% endfor %}
	</table>
    {% else %}
        <h2>There is no data to reset</h2>
    {% endif %}
{% endblock %}

templates/header.html
USER: LOGIN TIME: USER_TYPE:INCOME: 400.00 YESTERDAY: LIVE ACCOUNTS [155] CAP LEFT [1200.00/1600.75]WORKERS [7/22] Leads Per Hour [edu: 45, bizopp: 17] Income Per Hour [edu:450, bizopp: 80]OFFERS DEAD TODAY: [0], THIS WEEK: [7], LIVE OFFERS[bizopp=230, edu=65]ALERTS [7!]

templates/month_revenue.html
{% extends "base.html" %}

{% block title %} Month revenue {% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}ext/highcharts.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}ext/modules/exporting.js"></script>
    <script type="text/javascript">
	var datay = {{ datay|safe }};
    var datax = {{ datax|safe }};
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                defaultSeriesType: 'line',
                marginRight: 130,
                marginBottom: 25
            },
            title: { text: 'Monthly Revenue', x: -20 },
            xAxis: { categories: datay },
            yAxis: {
                title: { text: 'USD' },
                plotLines: [
                    {
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }
                ]
            },
            tooltip: {
                formatter: function() {
                    return '$ ' + this.y
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 100,
                borderWidth: 0
            },
            series: [
                {
                    name: 'Revenue',
                    data: datax
                }
            ]
        });
    })
</script>

{% endblock %}

{% block content %}
    <div id="container" style="width: 800px; height: 400px; margin: 0 auto"></div>
{% endblock %}


		

templates/networks.html
{% if networks %}
    You have 30 networks!<br>
    [Add Network]

    [Edit] [Delete] Hydra Network [2 accounts] [Add Account]
    [Edit] [Delete] Clickbooth: www.clickbooth.com [1 account] [Add Account]

    TABS LLC1|LLC2
    TABS ACCOUNTS|ACCOUNTING
    TABS ACCOUNT1 | ACCOUNT2 | ACCOUNT3
    TYPE: PRIMARY
    CAP: 45/100
    OFFERS: edu: 14, bizopp 23 [VIEW OFFERS]
    ===ACCOUNTING====
    PAYMENT PERIODS: 4
    PAID TIMES: 3
    payment period: 1/12-12/12 = 300/450|900, 85%|45%
    payment period: 1/12-12/12 = 300/450, 85%
    payment period: 1/12-12/12 = 300/450, 85%
    payment period: 1/12-12/12 = 300/450, [NO PAYMENTS ADDED]


    SWITCH LLC: SWITCH NETWORK: SWITCH ACCOUNT:
    ACCOUNT===
    NICHE:
    OFFERID|NAME|ADDED|SUBMITS|COST|MONEY_ASKED|MONEY_EARNED|conv%|CASH_RECIEVED|55%|33%|PPL|EPL

{% else %}
    Please add a network!
{% endif %}

templates/ping_session_include.html
{% if user.is_authenticated %}
<script type="text/javascript">
    $(function(){
        function ping(){
            $.get('{% url "accounts:ping" %}');

            setTimeout(ping, 1000)
        }

        ping();
    });
</script>
{% endif %}

templates/showqueue.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title></title>
</head>
<body>


    {% if queue %}
    <p>Junk Traffic Queue ({{ offer_queue_clicks_count }})</p>
        {% for url in queue %}
            <br>{{ url }}
        {% endfor %}
    {% endif %}

    {% if manual_queue %}
        <p>Manual/Emergency Queue ({{ manual_queue_clicks_count }})</p>
        {% for url in manual_queue %}
            <br>{{ url }}
        {% endfor %}
    {% endif %}

<p><a href="{% url "rotator.views.manualQueueCreate" %}">Add links to emergency queue?</a></p>
</body>
</html>